services:
  web:
    image: php:8.3-apache
    container_name: weather_site
    hostname: weather
    networks:
      - reverse-proxy
    volumes:
      - ./files:/var/www/html

networks:
  reverse-proxy:
    external: true
